### PR TITLE
Move deferred logging within append.

### PR DESCRIPTION
**Pull request by aerskine**
This fixes some lock order issues. Also adds a logger prefix which is used from TRACE level.

### CODE REVIEW

**Comment by aerskine** [comment]
@danielwegener have you had time to look at this yet?

**Comment by tpanagos** [comment]
I can tell you that I had a deadlock issue with my use of the appender with the Play 2.3 framework which this PR has gotten around. Without the PR (0.1.1 build from master) the server would freeze when the first log message was written and would not recover when the Kafka server was not running. With the PR, the server will continue to function without the Kafka server (though the fallback appender does not appear to kick-in).

**Comment by aerskine** [comment]
Thanks for the feedback @tpanagos ! Looks like @danielwegener is busy for now... hopefully we will hear from him soon.

**Comment by aerskine** [comment]
@tpanagos as for your observation of the fallback appender:

It is expected with the current PR that recursive calls are discarded (logback has a built in guard which serves this purpose).

Perhaps we need to have a broader discussion about this, since this PR will lead to some discarded kafka logs. This may be fine for some users, but not for others so perhaps should build in some flexibility.

A full blown InternalKafkaMessageStrategy is probably overkill. 

Perhaps a bean property or two could be added to the appender so that users can express their own choice for what happens to Kafka's internal messages.

The way I see it the main choice axes are:

1. Recursive call handling strategy (when Kafka internally logs during a log statement): the current PR discards these; other choices are defer, or log to fallback appender.

2. Kafka namespace logger handling strategy (when Kafka client logs, but not in a recursive call eg from the KafkaSender thread): the current PR defers these; other choices are discard, or log to fallback appender

The safest choices are to discard messages, or log to fallback (or some combination of these). The problem with deferring is illustrated in #36 ... when the log level is TRACE, enough log messages are produced internally to Kafka client to cause a runaway effect.

Eg say 15 of these TRACE messages are produced and we defer them. When it comes time to log the deferred messages then each one will kick off 15 more deferred messages, which quickly snowballs.  A quick way to see this in action is to set the level to `trace` in `logback-test.xml` and run `LogbackIntegrationIT`. Log messages from both the Kafka client *and* the embedded Kafka server quickly fill the deferred message queue, or slip past the `KAFKA_LOGGER_PREFIXES` because they are from some internal component namespace -- mayhem!

**Comment by danielwegener** [comment]
TBH I don't really like the idea to completely ignore logs from the kafka group or to generally drop messages produced by reentrance.

Imo we could solve all our current problems using the following strategy:

- We replace our unbounded  defer queue by a concurrent bounded queue that writes elements that do not fit into the queue synchronously to the fallbackAppenders. The size of this bounded queue is configurable (either in bytes or element count). (the elements should be prerendered ProducerRecords, such that the original deferred logging contexts can be gc'd early)
- The producer is initialized lazily and and asynchronously waits until the metadata is available for the logging topic.
- The blocking behavior of doAppend during missing topic metaData / pending metaData updates (during network partitions) is configurable as follows:
  - like now: simply block until the metaData becomes available
  - defer to the bounded queue
- Whenever the metadata is available during the beginning of a doAppend call, the remaining queue is submitted to the producer and then the actual message is written to the producer
- Kafka log-messages (even re-rentrant) are always added to bounded queue (they do not trigger the queue-drain, like you already suggested)

This will have the following effects:
- No deadlock by reentrant fine logging of the kafka client: All kafka messages are deferred and can only be _freed_ by a non-kafka-related log-message
- The doAppend does not block the application startup (if its okay that logs go to the fallbackAppender)
- no unbounded queue that would eventually cause an OOM if the application logs ONLY kafka messages
- this strategy _mimics_ the behavior of an producer itself that has valid metaData but is unable to talk to a leading broker (asynchronous buffering until)

OR a far simpler alternative:
- All kafka logs are sent to the fallbackAppenders directly
- Just log all messages to fallbackAppenders as soon as metadata become unavailable (optional)

@aerskine  Since you already made quite an effort to dig into this, I'd like to hear your thoughts on this :)

**Comment by danielwegener** [comment]
Okay, the pre-rendering actually does not work, since the fallbackAppender needs the original logging event. But we should use the `DeferredProcessingAware.prepareForDeferredProcessing` before we ever defer a logging event. Therefore we should make `includeCallerData` configurable (same as in `AsyncAppender`) so the caller is not eagerly extracted for each log message (which is quite expensive since it throws an artificial exception and analyzes the stacktrace)

**Comment by aerskine** [comment]
@danielwegener I like both options!

Perhaps we could consider a return of `KafkaAppenderBase<E>` to look after fallback appenders etc but not the actual append or producer creation? Then `KafkaAppender` could extend `KafkaAppenderBase<ILoggingEvent>` and provide something similar to what you suggest (although I am a bit uncertain about querying for topic metadata on every append), and offer a more forgiving (or at least configurable) reentrancy strategy.

A new `SimpleKafkaAppender` could provide your plan B: simple (non-lazy) initialization and log all Kafka logs directly to the fallback appenders.

**Comment by aerskine** [comment]
@danielwegener I was bored one evening and I started implementing your suggestion.

It was a few more changes than I would have liked! But the important thing is it seems to work.

Could you review what I've pushed?

Currently `deferUntilMetadataAvailable` is not enabled by default, but we could consider enabling it since it avoids the blocking behavior that others have noticed (eg the Spring users).

The `DEFAULT_QUEUE_SIZE` may be a bit small -- I lifted it from AsyncAppender, but thinking about it, a typical application could easily generate >256 messages while waiting for the initial Kafka metadata.

**Comment by aerskine** [comment]
I'm closing this MR due to inactivity.

**Pull request closed without merging**
