### PR TITLE
Changing KeyingStrategy names

### PR DESCRIPTION
**Pull request by BlackRider97**

### CODE REVIEW

**Comment by danielwegener** [comment]
Outch. Good catch. It's the same thing for all Keying Strategies. Would you mind fixing their names too in this PR?

**Comment by danielwegener** [comment]
Too bad documentation is not type-checked :)

**Comment by BlackRider97** [comment]
@danielwegener Sure. Its done now

**Comment by danielwegener** [comment]
oops - missed the notification. LGTM. cheers!

**Pull request merged**
