### PR TITLE
Updating auto ssl config

### PR DESCRIPTION
**Pull request by AshishHNP**
It would look something like this since its geared towards Heroku Kafka
Expects the environment variables in the config to contain private keys and certs

Not sure if its too specific of a usecase to be part of codebase though

### CODE REVIEW

**Comment by danielwegener** [comment]
Wow, could you please revert the formatting? The actual diff is quite hard to see like this :)

**Comment by danielwegener** [comment]
Okay, I think I got it. Sorry, I do not see it in the responsibility of this appender to create a temp key and truststore. I'd rather suggest you to implement a custom `LoggerStartupListener` for this use case that parses the env, creates the temp keystore files and makes the generated temp filenames available on the logger context such that they become available as variables on the kafka-appender configuration.

See https://stackoverflow.com/a/23969706/596869 as example.
Or do you see problems with that approach?

**Comment by AshishHNP** [comment]
Oh interesting, thanks @danielwegener . And yes, I felt it was a stretch and not really meant to be here as it was so specific to the use case of Heroku, but just thought I would throw it out there :)

Thanks for taking the time and looking at the PR and providing alternative solution

**Comment by danielwegener** [comment]
You are welcome - and thanks for *your* time to provide ideas and code!
If you see this as a common pattern and want to blog or provide gists about your solution, I'd be happy to reference them in the Readme/FAQ.

**Pull request closed without merging**
